version: "3"
services:
  backend:
    build:
      context: backend
    networks:
      - cloudgroup
    tty: true
    stdin_open: true
  frontend:
    build:
      context: frontend
    networks:
      - cloudgroup
    environment:
      PORT: 80
      REACT_APP_API_URL: /api
    depends_on:
      - backend
  app:
    build:
      context: app
    depends_on:
      - backend
      - frontend
    networks:
      - cloudgroup
    ports:
      - "80:80"

networks:
  cloudgroup:
    driver: bridge