version: "3"
services:
  backend:
    build: 
      context: backend
    ports:
      - "8001:8001"    
    networks:
      - cloudgroup
    tty: true
    stdin_open: true      
  frontend:
    build:
      context: frontend
    networks:
      - cloudgroup
    environment:
      PORT: 80
    depends_on: 
      - backend
    ports:
      - "80:80"   
      
networks:
  cloudgroup:
    driver: bridge      
