version: "3"
services:
  backend:
    build: 
      context: backend
    volumes:
      - .:/workspace:cached      
    # environment:
    ports:
      - "8001:8001"    
    networks:
      - cloudgroup
    tty: true
    stdin_open: true      
  frontend:
    build:
      context: frontend
    volumes:
      - .:/workspace:cached      
    networks:
      - cloudgroup
    environment:
      - PORT=80    
    depends_on: 
      - backend
    ports:
      - "80:80"
    tty: true
    stdin_open: true      
      
networks:
  cloudgroup:
    driver: bridge      
